### ISSUE TITLE
Compile with Emscripten

### ISSUE THREAD

**Issue by midzer** [ptitSeb/GLU#2]
Hi again,

additionally, I need this libary for a web port of Chromium BSU.

I have trouble compiling with Emscripten:

```
# Compile libstuff to libstuff.a
emconfigure ./configure
emmake make
```
I can get past the error from the first command by editing `configure`, but after second command I got:

```
wasm-ld-14: error: unknown argument: -retain-symbols-file
wasm-ld-14: error: unknown file type: .libs/libGLU.exp
```

Would be awesome if you can help me out, @ptitSeb 

Have a nice week
midzer

**Comment by ptitSeb** [comment]
Maybe you need to regenerate the `./configure`?

**Comment by midzer** [comment]
Okay, after `emmake make` I run

```
# Combine two object files into library file
emar rcs libfoo.a src1.o src2.o
```

for all `.o` files to create the static library.

Now, theres another symbol missing (I commented in another function in game source code):

```
error: undefined symbol: mgluPerspective
```

**Comment by ptitSeb** [comment]
this look like a mangling issue to me (because it's `mgluPerspective` and not just `gluPerspective`). Check the header your are using, they are probably forcing some mangling.

On the other hand, if the only function you are using from libGLU is `gluPerspective`, just copy the code of this function somewhere and don't link GLU, it will probably be easier.

**Comment by midzer** [comment]
Both of your proposed methods worked for me good.

The easy one worked like charm but looked like a quickfix, so I fixed the mangling problem by copying all files from `gl4es/include/GL` to `GLU/src/include/GL`.

Project builds and links properly now. Too bad there are runtime errors, where I have to dig deeper.

Thanks again for your support!
